### ISSUE TITLE
devcontainer config overwrites my dependabot.yml

### ISSUE THREAD

**Issue by 3f6a** [devcontainers/templates#274]
When I create a new devcontainer, for some reason vscode always attempts to rewrite my dependabot.yml file. It is trying to add this:

```
version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly
```

 Is this necessary? Could this snippet be *appended* to dependabot.yml, instead of overwriting my existing file?
